name: cmake-release

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: config cmake
        run: >-
          cmake
          -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=""
          -Bbuild
      - name: build
        run: cmake --build build --config Release
      - name: setup OS
        id: setup_os
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               echo "os=linux" >> "$GITHUB_OUTPUT"
               echo "file=build/bin/libqmap.so" >> "$GITHUB_OUTPUT"
          elif [ "$RUNNER_OS" == "Windows" ]; then
               choco install zip
               echo "os=win" >> "$GITHUB_OUTPUT"
               echo "file=build\src\qmap.dll" >> "$GITHUB_OUTPUT"
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
        shell: bash
      - name: pack
        run: zip -j libqmap-${{ steps.setup_os.outputs.os }}.zip ${{ steps.setup_os.outputs.file }}
